{{ generation_message }}
{{ from_image (index .Values "base_image") }}

LABEL org.opencontainers.image.authors="Martin Berwanger" \
      org.opencontainers.image.title="Tini Init System" \
      org.opencontainers.image.description="Minimal init system for containers with signal forwarding and zombie reaping"

RUN apk add --no-cache gnupg

# Install Tini for init use (reaps defunct processes and forwards signals)
RUN apkArch="$(apk --print-arch)"; \
  case "$apkArch" in \
    aarch64) export PLATFORM='-arm64' ;; \
    x86_64) export PLATFORM='' ;; \
  esac; \
  wget -O /tini https://github.com/krallin/tini/releases/download/{{ index .Values "version" }}/tini$PLATFORM ;\
  wget -O /tini.asc https://github.com/krallin/tini/releases/download/{{ index .Values "version" }}/tini$PLATFORM.asc

ARG KEYSERVERS="ipv4.pool.sks-keyservers.net pgp.mit.edu keyserver.ubuntu.com"
RUN --mount=type=cache,target=/var/cache/apk \
  set -eux; \
  for ks in ${KEYSERVERS}; do gpg --no-tty --keyserver "${ks}" --recv-keys {{ index .Values "gpg_key" }} && break; done \
  && gpg --no-tty --batch --verify /tini.asc /tini \
  && chmod +x /tini
