{{ generation_message }}

ARG TARGETPLATFORM
ARG TARGETARCH
ARG TARGETVARIANT

{{ from_image (index .Values "base_image") }}

RUN apk add --no-cache gnupg wget

# Install Tini for init use (reaps defunct processes and forwards signals)
RUN set -eux; \
  case "${TARGETARCH}" in \
    arm64|aarch64) export PLATFORM='-arm64' ;; \
    amd64|x86_64) export PLATFORM='' ;; \
    *) echo "Unsupported architecture: ${TARGETARCH}"; exit 1 ;; \
  esac; \
  wget -O /tini https://github.com/krallin/tini/releases/download/{{ index .Values "version" }}/tini${PLATFORM} ;\
  wget -O /tini.asc https://github.com/krallin/tini/releases/download/{{ index .Values "version" }}/tini${PLATFORM}.asc

ARG KEYSERVERS="keyserver.ubuntu.com keys.openpgp.org hkps://keyserver.ubuntu.com:443"
RUN --mount=type=cache,target=/var/cache/apk \
  set -eux; \
  for ks in ${KEYSERVERS}; do \
    echo "Trying keyserver: $ks"; \
    gpg --no-tty --keyserver-options timeout=10 --keyserver "${ks}" --recv-keys {{ index .Values "gpg_key" }} && break; \
  done \
  && gpg --no-tty --batch --verify /tini.asc /tini \
  && chmod +x /tini
