name: 'Build Single Dockerfile'
description: 'Build and optionally push a Docker image from a Dockerfile'
inputs:
  dockerfile_path:
    description: 'Path to the Dockerfile directory'
    required: true
  image_name:
    description: 'Image name (e.g., tini, core, python)'
    required: true
  image_tag:
    description: 'Image tag (e.g., v0.19.0, bookworm, 3.11)'
    required: true
  registry:
    description: 'Container registry URL'
    required: true
  registry_username:
    description: 'Registry username'
    required: true
  registry_password:
    description: 'Registry password'
    required: true
  image_repository:
    description: 'Full image repository path (e.g., ghcr.io/owner)'
    required: true
  push:
    description: 'Whether to push the image to the registry'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64  # Add ,linux/arm64 to enable ARM builds

    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - name: Generate build metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image_repository }}/${{ inputs.image_name }}
        tags: |
          type=raw,value=${{ inputs.image_tag }}
          type=raw,value=${{ inputs.image_tag }}-{{date 'YYYYMMDD'}}
          type=raw,value=${{ inputs.image_tag }}-{{sha}}
        labels: |
          org.opencontainers.image.title=${{ inputs.image_name }}:${{ inputs.image_tag }}
          org.opencontainers.image.description=Biograph ${{ inputs.image_name }} container image
          org.opencontainers.image.authors=Martin Berwanger
          org.opencontainers.image.vendor=Biograph
          org.opencontainers.image.version=${{ inputs.image_tag }}
          org.opencontainers.image.source={{url}}
          org.opencontainers.image.revision={{sha}}
          org.opencontainers.image.created={{isotime}}
          org.opencontainers.image.licenses=MIT

    - name: Get Dockerfile directory
      id: dockerfile_dir
      shell: bash
      run: echo "dir=$(dirname '${{ inputs.dockerfile_path }}')" >> $GITHUB_OUTPUT

    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        context: ${{ steps.dockerfile_dir.outputs.dir }}
        platforms: linux/amd64  # Add ,linux/arm64 to enable ARM builds
        push: ${{ inputs.push == 'true' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=${{ inputs.image_repository }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
        cache-to: type=inline
        build-args: |
          IMAGE_REPOSITORY=${{ inputs.image_repository }}
          BUILD_DATE={{date 'YYYYMMDD'}}
          BUILD_TIMESTAMP={{isotime}}
          COMMIT_SHA={{sha}}

    - name: Build summary
      shell: bash
      env:
        TAGS: ${{ steps.meta.outputs.tags }}
        PUSH_ENABLED: ${{ inputs.push }}
      run: |
        echo "🔨 Built image with tags:"
        echo "$TAGS" | while read -r tag; do
          if [ -n "$tag" ]; then
            echo "   📦 $tag"
          fi
        done

        if [ "$PUSH_ENABLED" == "true" ]; then
          echo "✅ Images pushed to registry"
        else
          echo "⏭️  Images built but not pushed (PR or non-master branch)"
        fi
