{{ generation_message }}
{{ from_image (index .Values "base_image") }}

LABEL org.opencontainers.image.authors="Martin Berwanger" \
      org.opencontainers.image.title="Python {{ index .Values "python_version" }}" \
      org.opencontainers.image.description="Python programming language runtime with pip and pipenv for application development"

USER root

ARG PYTHON_VERSION={{ index .Values "python_version" }}
ARG PYTHON_MAJOR_MINOR_VERSION={{ index .Values "python_build_version" }}
ARG PIP_VERSION={{ index .Values "pip_version" }}
ARG PYTHON_GPG_KEY={{ index .Values "python_pgp_key_id" }}

# Install Python build dependencies and compile from source
RUN set -eux; \
    apt-get update \
 && apt-get install -y --no-install-recommends \
        build-essential \
        libbz2-dev \
        libffi-dev \
        libgdbm-dev \
        liblzma-dev \
        libncurses5-dev \
        libnss3-dev \
        libreadline-dev \
        libsqlite3-dev \
        libssl-dev \
        xz-utils \
        zlib1g-dev \
 && cd /tmp \
 && curl -fsSLO https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tar.xz \
 && curl -fsSLO https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tar.xz.asc \
 && export GNUPGHOME="$(mktemp -d)" \
 && gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys ${PYTHON_GPG_KEY} || \
    gpg --batch --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys ${PYTHON_GPG_KEY} \
 && gpg --verify Python-${PYTHON_VERSION}.tar.xz.asc Python-${PYTHON_VERSION}.tar.xz \
 && gpgconf --kill all \
 && rm -rf "$GNUPGHOME" \
 && tar -xf Python-${PYTHON_VERSION}.tar.xz \
 && cd Python-${PYTHON_VERSION} \
 && ./configure --enable-optimizations --with-lto --enable-shared \
 && make -j$(nproc) altinstall \
 && ldconfig \
 && cd / \
 && rm -rf /tmp/Python-${PYTHON_VERSION}* \
 && python${PYTHON_MAJOR_MINOR_VERSION} --version

# Install pip and pipenv
RUN pip${PYTHON_MAJOR_MINOR_VERSION} install --no-cache-dir --upgrade pip==${PIP_VERSION} \
 && pip${PYTHON_MAJOR_MINOR_VERSION} install --no-cache-dir pipenv

# Setup working directory and user
WORKDIR /usr/src/app/
RUN chown docker:docker .

USER docker

# Initialize pipenv with specific Python version
RUN pipenv --python ${PYTHON_MAJOR_MINOR_VERSION}
